export const APP_CONSTANTS = {
  LANGUAGES: {
    HINDI: "hindi",
    ENGLISH: "english",
    BENGALI: "bengali",
    TAMIL: "tamil",
    TELUGU: "telugu",
    MARATHI: "marathi",
    GUJARATI: "gujarati",
    KANNADA: "kannada",
    MALAYALAM: "malayalam",
    PUNJABI: "punjabi",
    ODIA: "odia",
    ASSAMESE: "assamese",
    URDU: "urdu",
  },
  LANGUAGE_NAMES: {
    hindi: "हिन्दी",
    english: "English",
    bengali: "বাংলা",
    tamil: "தமிழ்",
    telugu: "తెలుగు",
    marathi: "मराठी",
    gujarati: "ગુજરાતી",
    kannada: "ಕನ್ನಡ",
    malayalam: "മലയാളം",
    punjabi: "ਪੰਜਾਬੀ",
    odia: "ଓଡ଼ିଆ",
    assamese: "অসমীয়া",
    urdu: "اردو",
  },
  LANGUAGE_CODES: {
    hindi: "hi-IN",
    english: "en-IN",
    bengali: "bn-IN",
    tamil: "ta-IN",
    telugu: "te-IN",
    marathi: "mr-IN",
    gujarati: "gu-IN",
    kannada: "kn-IN",
    malayalam: "ml-IN",
    punjabi: "pa-IN",
    odia: "or-IN",
    assamese: "as-IN",
    urdu: "ur-IN",
  },
  PAGES: {
    HOME: "home",
    DEVICES: "devices",
    LEARN: "learn",
    MARKETPLACE: "marketplace",
    PROFILE: "profile",
  },
  CONNECTION_STATUS: {
    ONLINE: "online",
    OFFLINE: "offline",
  },
  VOICE_ASSISTANT_STATES: {
    IDLE: "idle",
    LISTENING: "listening",
    PROCESSING: "processing",
    RESPONDING: "responding",
  },
  AI_FEATURES: {
    CROP_ADVISORY: "crop_advisory",
    PEST_DETECTION: "pest_detection",
    WEATHER_PREDICTION: "weather_prediction",
    MARKET_PRICE_FORECAST: "market_price_forecast",
    SOIL_ANALYSIS: "soil_analysis",
  },
};

export const TRANSLATIONS = {
  [APP_CONSTANTS.LANGUAGES.HINDI]: {
    home: "होम",
    devices: "उपकरण",
    learn: "सीखें",
    marketplace: "बाजार",
    profile: "प्रोफाइल",
    online: "ऑनलाइन",
    offline: "ऑफलाइन सलाह",
    voicePrompt: "नमस्ते, आज की फसल की स्थिति के बारे में पूछने के लिए बोलें...",
    listening: "सुन रहा हूँ...",
    deviceStatus: "आपके उपकरणों की स्थिति",
    tasks: "आज के कार्य",
    taskList: "कार्य सूची",
    weather: "मौसम पूर्वानुमान",
    advisoryTitle: "AgriDidi की सलाह",
    academyTitle: "SakhiShakti अकादमी",
    marketplaceTitle: "AgroChain मार्केटप्लेस",
    schemes: "सरकारी सहायता योजनाएँ",
    viewCourses: "सभी पाठ्यक्रम देखें",
    viewMarket: "बाजार देखें",
    addProduct: "उत्पाद जोड़ें",
    startNow: "अभी शुरू करें",
    saveOffline: "ऑफलाइन सहेजें",
    viewDetails: "विवरण देखें",
    apply: "आवेदन करें",
    watchVideo: "वीडियो देखें",
    joinGroup: "संघ में शामिल हों",
    lastSale: "पिछला विक्रय",
    currentProduct: "वर्तमान उत्पाद",
    marketPrice: "बाजार मूल्य",
    progress: "प्रगति",
    connectedStatus: "संयोजित",
    onlineStatus: "ऑनलाइन",
    battery: "बैटरी",
    solarPower: "सौर ऊर्जा पर",
    soil: "मिट्टी की नमी",
    temperature: "वायु तापमान",
    humidity: "आर्द्रता",
    updateTime: "अपडेट समय",
    startTask: "शुरू करें",
    humidityWeather: "आर्द्रता",
    wind: "हवा",
    rainfall: "वर्षा",
    updated: "अपडेट",
    level: "लेवल",
    points: "अंक",
    completed: "पूरा हुआ",
    pending: "बाकी",
    important: "महत्वपूर्ण",
    changeLanguage: "भाषा बदलें",
    aiCropAdvisory: "AI फसल सलाह",
    aiPestDetection: "AI कीट पहचान",
    aiSoilAnalysis: "AI मिट्टी विश्लेषण",
    aiForecast: "AI बाजार पूर्वानुमान",
    scanImage: "छवि स्कैन करें",
    takePhoto: "फोटो लें",
    uploadImage: "छवि अपलोड करें",
    analysisResult: "विश्लेषण परिणाम",
    detectPest: "कीट का पता लगाएं",
    soilHealth: "मिट्टी का स्वास्थ्य",
    marketTrends: "बाज़ार रुझान",
    confidence: "विश्वास स्तर",
    aiWeatherPrediction: "AI मौसम पूर्वानुमान",
    aiWeatherDescription: "आपके क्षेत्र के लिए सटीक मौसम पूर्वानुमान प्राप्त करें",
    getForecast: "पूर्वानुमान प्राप्त करें",
    enterLocation: "स्थान दर्ज करें",
    days: "दिन",
    farmingAdvice: "खेती सलाह",
  },
  [APP_CONSTANTS.LANGUAGES.ENGLISH]: {
    home: "Home",
    devices: "Devices",
    learn: "Learn",
    marketplace: "Market",
    profile: "Profile",
    online: "Online",
    offline: "Offline Advice",
    voicePrompt: "Hello, speak to ask about today's crop status...",
    listening: "Listening...",
    deviceStatus: "Your Device Status",
    tasks: "Today's Tasks",
    taskList: "Task List",
    weather: "Weather Forecast",
    advisoryTitle: "AgriDidi's Advice",
    academyTitle: "SakhiShakti Academy",
    marketplaceTitle: "AgroChain Marketplace",
    schemes: "Government Support Schemes",
    viewCourses: "View All Courses",
    viewMarket: "View Market",
    addProduct: "Add Product",
    startNow: "Start Now",
    saveOffline: "Save Offline",
    viewDetails: "View Details",
    apply: "Apply",
    watchVideo: "Watch Video",
    joinGroup: "Join Group",
    lastSale: "Last Sale",
    currentProduct: "Current Product",
    marketPrice: "Market Price",
    progress: "Progress",
    connectedStatus: "Connected",
    onlineStatus: "Online",
    battery: "Battery",
    solarPower: "Solar Powered",
    soil: "Soil Moisture",
    temperature: "Air Temperature",
    humidity: "Humidity",
    updateTime: "Update Time",
    startTask: "Start Task",
    humidityWeather: "Humidity",
    wind: "Wind",
    rainfall: "Rainfall",
    updated: "Updated",
    level: "Level",
    points: "Points",
    completed: "Completed",
    pending: "Pending",
    important: "Important",
    changeLanguage: "Change Language",
    aiCropAdvisory: "AI Crop Advisory",
    aiPestDetection: "AI Pest Detection",
    aiSoilAnalysis: "AI Soil Analysis",
    aiForecast: "AI Market Forecast",
    scanImage: "Scan Image",
    takePhoto: "Take Photo",
    uploadImage: "Upload Image",
    analysisResult: "Analysis Result",
    detectPest: "Detect Pest",
    soilHealth: "Soil Health",
    marketTrends: "Market Trends",
    confidence: "Confidence",
    aiWeatherPrediction: "AI Weather Prediction",
    aiWeatherDescription: "Get accurate weather forecasts for your region",
    getForecast: "Get Forecast",
    enterLocation: "Enter Location",
    days: "Days",
    farmingAdvice: "Farming Advice",
  },
  [APP_CONSTANTS.LANGUAGES.BENGALI]: {
    home: "হোম",
    devices: "যন্ত্রপাতি",
    learn: "শিখুন",
    marketplace: "বাজার",
    profile: "প্রোফাইল",
    online: "অনলাইন",
    offline: "অফলাইন পরামর্শ",
    voicePrompt: "নমস্কার, আজকের ফসলের অবস্থা সম্পর্কে জিজ্ঞাসা করতে কথা বলুন...",
    listening: "শুনছি...",
    deviceStatus: "আপনার ডিভাইসের অবস্থা",
    tasks: "আজকের কাজ",
    taskList: "কাজের তালিকা",
    weather: "আবহাওয়া পূর্বাভাস",
    advisoryTitle: "AgriDidi-র পরামর্শ",
    academyTitle: "SakhiShakti একাডেমি",
    marketplaceTitle: "AgroChain মার্কেটপ্লেস",
    schemes: "সরকারি সহায়তা প্রকল্প",
    viewCourses: "সকল কোর্স দেখুন",
    viewMarket: "বাজার দেখুন",
    addProduct: "পণ্য যোগ করুন",
    startNow: "এখনই শুরু করুন",
    saveOffline: "অফলাইন সংরক্ষণ করুন",
    viewDetails: "বিস্তারিত দেখুন",
    apply: "আবেদন করুন",
    watchVideo: "ভিডিও দেখুন",
    joinGroup: "গ্রুপে যোগ দিন",
    lastSale: "শেষ বিক্রয়",
    currentProduct: "বর্তমান পণ্য",
    marketPrice: "বাজার দাম",
    progress: "অগ্রগতি",
    connectedStatus: "সংযুক্ত",
    onlineStatus: "অনলাইন",
    battery: "ব্যাটারি",
    solarPower: "সৌর শক্তিতে চালিত",
    soil: "মাটির আর্দ্রতা",
    temperature: "বায়ু তাপমাত্রা",
    humidity: "আর্দ্রতা",
    updateTime: "আপডেট সময়",
    startTask: "কাজ শুরু করুন",
    humidityWeather: "আর্দ্রতা",
    wind: "বাতাস",
    rainfall: "বৃষ্টিপাত",
    updated: "আপডেট করা হয়েছে",
    level: "স্তর",
    points: "পয়েন্ট",
    completed: "সম্পন্ন",
    pending: "বাকি আছে",
    important: "গুরুত্বপূর্ণ",
    changeLanguage: "ভাষা পরিবর্তন করুন",
    aiCropAdvisory: "AI ফসল পরামর্শ",
    aiPestDetection: "AI কীটপতঙ্গ সনাক্তকরণ",
    aiSoilAnalysis: "AI মাটি বিশ্লেষণ",
    aiForecast: "AI বাজার পূর্বাভাস",
    scanImage: "ছবি স্ক্যান করুন",
    takePhoto: "ছবি তুলুন",
    uploadImage: "ছবি আপলোড করুন",
    analysisResult: "বিশ্লেষণ ফলাফল",
    detectPest: "কীটপতঙ্গ সনাক্ত করুন",
    soilHealth: "মাটির স্বাস্থ্য",
    marketTrends: "বাজারের প্রবণতা",
  },
  [APP_CONSTANTS.LANGUAGES.TAMIL]: {
    home: "முகப்பு",
    devices: "சாதனங்கள்",
    learn: "கற்றுக்கொள்ளுங்கள்",
    marketplace: "சந்தை",
    profile: "சுயவிவரம்",
    changeLanguage: "மொழியை மாற்றவும்",
    aiCropAdvisory: "AI பயிர் ஆலோசனை",
    aiPestDetection: "AI பூச்சி கண்டறிதல்",
    aiSoilAnalysis: "AI மண் பகுப்பாய்வு",
    aiForecast: "AI சந்தை முன்னறிவிப்பு",
  },
  [APP_CONSTANTS.LANGUAGES.TELUGU]: {
    home: "హోమ్",
    devices: "పరికరాలు",
    learn: "నేర్చుకోండి",
    marketplace: "మార్కెట్",
    profile: "ప్రొఫైల్",
    changeLanguage: "భాషను మార్చండి",
    aiCropAdvisory: "AI పంట సలహా",
    aiPestDetection: "AI పురుగు గుర్తింపు",
    aiSoilAnalysis: "AI నేల విశ్లేషణ",
    aiForecast: "AI మార్కెట్ ఫోర్కాస్ట్",
  },
};
