export const APP_CONSTANTS = {
  LANGUAGES: {
    HINDI: "hindi",
    ENGLISH: "english",
  },
  PAGES: {
    HOME: "home",
    DEVICES: "devices",
    LEARN: "learn",
    MARKETPLACE: "marketplace",
    PROFILE: "profile",
  },
  CONNECTION_STATUS: {
    ONLINE: "online",
    OFFLINE: "offline",
  },
  VOICE_ASSISTANT_STATES: {
    IDLE: "idle",
    LISTENING: "listening",
    PROCESSING: "processing",
    RESPONDING: "responding",
  },
};

export const TRANSLATIONS = {
  [APP_CONSTANTS.LANGUAGES.HINDI]: {
    home: "होम",
    devices: "उपकरण",
    learn: "सीखें",
    marketplace: "बाजार",
    profile: "प्रोफाइल",
    online: "ऑनलाइन",
    offline: "ऑफलाइन सलाह",
    voicePrompt: "नमस्ते, आज की फसल की स्थिति के बारे में पूछने के लिए बोलें...",
    listening: "सुन रहा हूँ...",
    deviceStatus: "आपके उपकरणों की स्थिति",
    tasks: "आज के कार्य",
    taskList: "कार्य सूची",
    weather: "मौसम पूर्वानुमान",
    advisoryTitle: "AgriDidi की सलाह",
    academyTitle: "SakhiShakti अकादमी",
    marketplaceTitle: "AgroChain मार्केटप्लेस",
    schemes: "सरकारी सहायता योजनाएँ",
    viewCourses: "सभी पाठ्यक्रम देखें",
    viewMarket: "बाजार देखें",
    addProduct: "उत्पाद जोड़ें",
    startNow: "अभी शुरू करें",
    saveOffline: "ऑफलाइन सहेजें",
    viewDetails: "विवरण देखें",
    apply: "आवेदन करें",
    watchVideo: "वीडियो देखें",
    joinGroup: "संघ में शामिल हों",
    lastSale: "पिछला विक्रय",
    currentProduct: "वर्तमान उत्पाद",
    marketPrice: "बाजार मूल्य",
    progress: "प्रगति",
    connectedStatus: "संयोजित",
    onlineStatus: "ऑनलाइन",
    battery: "बैटरी",
    solarPower: "सौर ऊर्जा पर",
    soil: "मिट्टी की नमी",
    temperature: "वायु तापमान",
    humidity: "आर्द्रता",
    updateTime: "अपडेट समय",
    startTask: "शुरू करें",
    humidityWeather: "आर्द्रता",
    wind: "हवा",
    rainfall: "वर्षा",
    updated: "अपडेट",
    level: "लेवल",
    points: "अंक",
    completed: "पूरा हुआ",
    pending: "बाकी",
    important: "महत्वपूर्ण",
  },
  [APP_CONSTANTS.LANGUAGES.ENGLISH]: {
    home: "Home",
    devices: "Devices",
    learn: "Learn",
    marketplace: "Market",
    profile: "Profile",
    online: "Online",
    offline: "Offline Advice",
    voicePrompt: "Hello, speak to ask about today's crop status...",
    listening: "Listening...",
    deviceStatus: "Your Device Status",
    tasks: "Today's Tasks",
    taskList: "Task List",
    weather: "Weather Forecast",
    advisoryTitle: "AgriDidi's Advice",
    academyTitle: "SakhiShakti Academy",
    marketplaceTitle: "AgroChain Marketplace",
    schemes: "Government Support Schemes",
    viewCourses: "View All Courses",
    viewMarket: "View Market",
    addProduct: "Add Product",
    startNow: "Start Now",
    saveOffline: "Save Offline",
    viewDetails: "View Details",
    apply: "Apply",
    watchVideo: "Watch Video",
    joinGroup: "Join Group",
    lastSale: "Last Sale",
    currentProduct: "Current Product",
    marketPrice: "Market Price",
    progress: "Progress",
    connectedStatus: "Connected",
    onlineStatus: "Online",
    battery: "Battery",
    solarPower: "Solar Powered",
    soil: "Soil Moisture",
    temperature: "Air Temperature",
    humidity: "Humidity",
    updateTime: "Update Time",
    startTask: "Start Task",
    humidityWeather: "Humidity",
    wind: "Wind",
    rainfall: "Rainfall",
    updated: "Updated",
    level: "Level",
    points: "Points",
    completed: "Completed",
    pending: "Pending",
    important: "Important",
  },
};
